### ISSUE TITLE
Trying to get Reporting ---- retrofitting cucumber-protractor-framework issue (im using "cucumber": "1.3.2")

### ISSUE THREAD

**Issue by kdp88** [jan-molak/serenity-js#196] opened 2018-03-23 14:23 UTC
basically the same issue as in [this issue](https://github.com/jan-molak/serenity-js/issues/163url).

 followed the guide found on http://serenity-js.org/overview/retrofitting.html 

I have the following inside package.json 

```
{
  "license": "COMMERCIAL",
  "name": "app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "npm run arc-merge-languages && ng serve",
    "build": "npm run arc-merge-languages && ng build",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "arc-merge-languages": "node -e \"require('./node_modules/@arc/arc-frontend-utils/src/index').mergeLanguageFiles()\"",
    "packagr": "ng-packagr -p ./arc-seed-frontend/ng-package.json",
    "packonly": "ng-packagr -p arc-seed-frontend/ng-package.json",
    "preprotractor": "webdriver-manager update --standalone --versions.standalone 3.0.1",
    "protractor": "protractor ./protractor.conf.js",
    "test": "npm run protractor --silent",
    "pretest": "serenity update",
    "report": "serenity run"
  },
  "keywords": [
    "serenity-js",
    "protractor",
    "cucumber"
  ],
  "private": false,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.0.4",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ngrx/effects": "^5.0.1",
    "@ngrx/entity": "^5.0.1",
    "@ngrx/router-store": "^5.0.0",
    "@ngrx/store": "^5.0.0",
    "@ngrx/store-devtools": "^5.0.0",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^2.0.1",
    "web-animations-js": "^2.3.1",
    "browser-sync": "^2.23.5",
    "chart.js": "^2.7.1",
    "core-js": "^2.5.3",
    "font-awesome": "^4.7.0",
    "fullcalendar": "^3.8.0",
    "jquery": "^3.2.1",
    "moment": "^2.17.1",
    "primeng": "^5.2.0",
    "quill": "^1.3.4",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20",
    "intl": "^1.2.5",
    "serenity-js": "^1.10.6"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.4",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/chai": "4.0.0",
    "@types/chai-as-promised": "0.0.31",
    "@types/cucumber": "1.3.1",
    "@types/jasmine": "~2.8.4",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~9.3.0",
    "angular4-swagger-client-generator": "~0.1.12",
    "chai": "4.0.2",
    "chai-as-promised": "7.0.0",
    "chai-smoothie": "^0.3.2",
    "chrome-headless-launcher": "^0.1.5",
    "codelyzer": "4.0.2",
    "cpx": "^1.5.0",
    "cucumber": "1.3.2",
    "glob": "7.1.2",
    "jasmine-core": "^2.8.0",
    "jasmine-marbles": "^0.2.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.3",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^2.0.0",
    "ng-swagger-gen": "^0.10.0",
    "ngc": "^1.0.0",
    "protractor": "^5.2.2",
    "protractor-cucumber-framework": "3.1.2",
    "serenity-cli": "^0.8.0",
    "source-map-explorer": "^1.5.0",
    "ts-node": "^4.1.0",
    "tsickle": "^0.27.2",
    "tslint": "^5.9.1",
    "typescript": "^2.6.2"
  }
}
```
i have the following in my protractor.conf.js

```
const
    glob         = require('glob'),
    protractor   = require.resolve('protractor'),
    node_modules = protractor.substring(0, protractor.lastIndexOf('node_modules') + 'node_modules'.length),
    seleniumJar  = glob.sync(`${node_modules}/protractor/**/selenium-server-standalone-*.jar`).pop();

exports.config = {

    baseUrl: 'https://url/login',

    seleniumServerJar: seleniumJar,

    // https://github.com/angular/protractor/blob/master/docs/timeouts.md
    allScriptsTimeout: 110000,

    disableChecks: true,
    restartBrowserBetweenTests: true,
    // https://github.com/protractor-cucumber-framework/protractor-cucumber-framework#uncaught-exceptions
    ignoreUncaughtExceptions: true,

    framework: 'custom',
    frameworkPath: require.resolve('serenity-js'),
    specs: [ 'e2e/features/**/*.feature' ],

    cucumberOpts: {
        require:    [ 'e2e/features/**/*.ts' ],
        format:     'pretty',
        compiler:   'ts:ts-node/register'
    },

    capabilities: {
        browserName: 'chrome',
        chromeOptions: {
            args: [
                'disable-infobars'
                // 'incognito',
                // 'disable-extensions',
                // 'show-fps-counter=true'
            ]
        }
    }
};
```
when i run npm test i get the following:

```
[10:15:25] E/launcher - Error: TypeError: _.chain(...).toPairs is not a function
    at CucumberTestFramework.argumentsFrom (C:\dev\account-service-frontend_test\node_modules\serenity-js\src\serenity-cucumber\cucumber_test_framework.ts:53:40)
    at new CucumberTestFramework (C:\dev\account-service-frontend_test\node_modules\serenity-js\src\serenity-cucumber\cucumber_test_framework.ts:16:25)
    at TestFrameworkDetector.tryToInstantiate (C:\dev\account-service-frontend_test\node_modules\serenity-js\src\serenity-protractor\framework\test_framework_detector.ts:45:37)
    at TestFrameworkDetector.frameworkFor (C:\dev\account-service-frontend_test\node_modules\serenity-js\src\serenity-protractor\framework\test_framework_detector.ts:14:25)
    at new SerenityProtractorFramework (C:\dev\account-service-frontend_test\node_modules\serenity-js\src\serenity-protractor\framework\serenity_protractor_framework.ts:36:38)
    at Object.run (C:\dev\account-service-frontend_test\node_modules\serenity-js\src\serenity-protractor\framework\serenity_protractor_framework.ts:21:12)
    at q.then.then.then.then (C:\dev\account-service-frontend_test\node_modules\protractor\built\runner.js:405:43)
    at _fulfilled (C:\dev\account-service-frontend_test\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\dev\account-service-frontend_test\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\dev\account-service-frontend_test\node_modules\q\q.js:796:13)
[10:15:25] E/launcher - Process exited with error code 100
npm ERR! Test failed.  See above for more details.

```
Any advice is appreciated

**Comment by jan-molak** [comment] 2018-03-26 15:12
Hi there! It looks like issue #184 fixed in version [1.10.7](http://serenity-js.org/changelog.html#1107-2018-03-18) of `serenity-js`. Could you please pull in the latest version and check if that solves the problem?

I need to improve how those changelogs are published so that the fixes are easier to find.

**Comment by nshelms** [comment] 2018-03-26 15:46
npm doesn't see the 1.10.7 version.

**Comment by jan-molak** [comment] 2018-04-30 23:46
I'll close this ticket for now, but if the issue is still there please let me know and we can reopen it.

**Closed by jan-molak** 2018-04-30 23:46 UTC
Labels: awaiting feedback
