### ISSUE TITLE
css can't be used to have a dynamic selector

### ISSUE THREAD

**Issue by CamiloCode** [jan-molak/serenity-js#92] opened 2017-08-30 19:52 UTC
When I try to do the following it fails:

 ```
static my_selector = Target.the('my_selector')
      .located(by.css('#registry_validation_dropdown_idType li:nth-of-type("{0}")'));
```
but it works with xpath
```

 static my_selector = Target.the('my_selector')
      .located(by.xpath('//p-dropdown[@id='my_selector']//li["{0}"]'));
```

**Comment by jan-molak** [comment] 2017-09-25 15:21
This looks like a duplicate of #93? Please feel free to reopen if that's not the case.

**Closed by jan-molak** 2017-09-25 15:21 UTC

**Comment by CamiloCode** [comment] 2017-09-26 16:42
@jan-molak its exactly the same, but for me , it didnt work anything when I used css. can you make sure it works for a dynamic css selector for you?. I saw the commit you did but its only Xpath
