### ISSUE TITLE
Rerun of failed Scenarios

### ISSUE THREAD

**Issue by AbhineetSharmax** [jan-molak/serenity-js#371] opened 2019-11-25 10:11 UTC
Hi @jan-molak , 

Thank you for all the hardwork.

Is there any option with which we may re run the failed scenarios? Please suggest.

Thanks,
Abhineet Sharma

**Comment by abhinaba1080** [comment] 2019-11-25 10:12
This will help you :https://github.com/jan-molak/serenity-js/issues/101

**Comment by jan-molak** [comment] 2019-11-25 16:38
Thanks @abhinaba1080 - closing as a duplicate of #101

**Closed by jan-molak** 2019-11-25 16:38 UTC
