### ISSUE TITLE
report is not complete

### ISSUE THREAD

**Issue by aminda007** [jan-molak/serenity-js#72] opened 2017-07-07 16:48 UTC
I posted the question in https://stackoverflow.com/questions/44975738/serenity-js-not-showing-all-test-cases-in-the-report  
Appreciate your wonderful effort in this.

**Comment by jan-molak** [comment] 2017-07-08 11:03
Hi there! Report generation happens in [two phases](http://serenity-js.org/from-scripts-to-serenity/making-the-tests-speak-for-themselves.html): the first phase produces one `json` file per executed scenario, the second phase converts those `json` files into the `HTML` report.

Could you try to run your tests and let me know if you're getting a correct number of `json` files generated?

Also, are those 40 unique tests, or 20 unique tests executed in 2 different browsers?

Thanks!
Jan

**Comment by aminda007** [comment] 2017-07-08 14:31
Hi, 
All tests are unique and I used only chrome browser for testing.
Thanks a lot for the reply.

**Comment by jan-molak** [comment] 2017-07-15 22:52
It's possible that the issue you're seeing was caused by how the report file names were generated.
I've changed the algorithm in 1.8.0, so could you please give it a try and let me know if the issue is still there?

Thanks,
Jan

**Comment by aminda007** [comment] 2017-07-24 11:09
Yeah.. it worked for me. Sorry I couldn't reply you sooner. But the ordering issue is still there. So still I can only order the test cases according to alphabet and not in the order which they were executed.

**Comment by jan-molak** [comment] 2017-07-24 16:27
No worries, so you're getting all the 40 test scenarios, but you'd also like to be able to order them by the time they were executed, is that right?

**Comment by aminda007** [comment] 2017-07-24 16:32
That's right.. Again thanks a lot for your attention on this.

**Comment by jan-molak** [comment] 2017-07-24 22:04
Great, thank for clarifying 👍 So I'll close this ticket as it's related to report files getting overwritten and perhaps I could ask you to raise a new one describing the sorting functionality you'd like?

Thanks!

**Closed by jan-molak** 2017-07-24 22:04 UTC
Labels: ready
